import {L} from './ko.js?v=35';
import {MAX_DECK,UNITS,ENEMIES,U,E,STAGES,WORLDS,TEXT,TUTORIAL_PACING as T,BOARD as G} from './data.js?v=35';
import {Simulation} from './sim.js?v=35';import {SaveStore} from './save.js?v=35';import {AudioManager} from './audio.js?v=35';import {Renderer} from './render.js?v=35';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const query=new URLSearchParams(location.search),test=query.has('test');
class App{
 constructor(){this.canvas=$('#game');this.ui=$('#ui');this.renderer=new Renderer(this.canvas);this.save=new SaveStore(test?'pj-test-'+(query.get('test')||'default'):'pharmacy-jinsang-v1');this.audio=new AudioManager(this.save.data.settings);this.scene='loading';this.uiTime=0;this.cineTime=0;this.speed=1;this.selected=null;this.stamp=false;this.stageId=Math.min(20,this.save.data.cleared+1);this.deck=[...this.save.data.deck];this.modal=null;this.reasons=new Set();this.banner=null;this.accum=0;this.inputLog=[];this.ui.innerHTML=`<div class="modal-wrap"><div class="modal"><div class="eyebrow">PHARMACY & JINSANG</div><h1 class="title">${L.loading}</h1><p class="sub">${L.loadingHint}</p></div></div>`;this.resize();}
 async init(){try{await this.renderer.load();this.scene='hub';this.renderUI();this.resize();window.addEventListener('resize',()=>this.resize());this.ui.addEventListener('click',e=>this.click(e));this.ui.addEventListener('input',e=>this.settingsInput(e));this.canvas.addEventListener('pointerdown',e=>this.pointer(e));document.addEventListener('visibilitychange',()=>{if(document.hidden){this.reasons.add('background');if(this.sim)this.sim.pauses.add('background');this.audio.pause(true);}else if(['battle','ending','ko','defeat','aftermath'].includes(this.scene)){if(!this.modal)this.modal='pause';this.renderUI();}else{this.reasons.delete('background');this.audio.pause(false);}});$('#rotate-pause').onclick=()=>{this.pause();};document.addEventListener('keydown',e=>{if(e.key==='Escape')this.pause();});if(this.save.warning)this.toast(this.save.warning);this.last=performance.now();requestAnimationFrame(t=>this.frame(t));}catch(e){this.ui.innerHTML=`<div class="screen"><h1>${L.loadError}</h1><p>${esc(e.message)}</p><button class="btn" onclick="location.reload()">${L.reload}</button></div>`;console.error(e);}}
 resize(){let host=$('#app'),cs=getComputedStyle(host),pw=innerWidth-parseFloat(cs.paddingLeft)-parseFloat(cs.paddingRight),ph=innerHeight-parseFloat(cs.paddingTop)-parseFloat(cs.paddingBottom),scale=Math.min(pw/1200,ph/675);this.w=1200*scale;this.h=675*scale;this.renderer.resize(this.w,this.h,Math.min(2,devicePixelRatio||1));this.ui.style.width=this.w+'px';this.ui.style.height=this.h+'px';if(innerHeight>innerWidth&&(['battle','ending','ko','defeat','aftermath'].includes(this.scene))){this.reasons.add('orientation');this.sim?.pauses.add('orientation');this.audio.pause(true);}else if(this.reasons.has('orientation')){if(!this.modal)this.modal='pause';this.renderUI();}}
 toast(text){let el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),2600);}
 thumb(id){return this.renderer.thumbs[id]||'';}
 btn(action,text,cls='',extra=''){return `<button class="btn ${cls}" data-action="${action}" ${extra}>${text}</button>`;}
 goto(scene){this.scene=scene;this.modal=null;this.reasons.clear();this.accum=0;this.audio.theme(scene==='hub'||scene==='map'||scene==='deck'?'hub':'world0');this.renderUI();}
 unlocked(){return UNITS.filter(u=>u.unlock<=this.save.data.cleared+1);}
 start(stageId=this.stageId,{tutorial=!this.save.data.tutorial,seed=stageId*1979}={}){this.stageId=stageId;this.sim=new Simulation(stageId,this.deck,seed,{tutorial});this.scene='battle';this.modal=null;this.reasons.clear();this.selected=null;this.stamp=false;this.speed=1;this.cineTime=0;this.event=null;this.banner=null;this.accum=0;this.save.data.deck=[...this.deck];this.save.write();this.audio.theme('world'+this.sim.stage.world);this.audio.layer=0;this.renderUI();this.resize();}
 pause(){if(this.modal&&this.modal!=='pause')return;if(!['battle','ending','ko','defeat','aftermath'].includes(this.scene))return;this.reasons.add('manual');this.sim?.pauses.add('manual');this.modal='pause';this.audio.pause(true);this.renderUI();}
 resume(){if(document.hidden||innerHeight>innerWidth)return;this.reasons.clear();this.sim?.pauses.clear();this.modal=null;this.audio.pause(false);this.accum=0;this.renderUI();}
 click(e){let b=e.target.closest('[data-action]');if(!b||b.disabled)return;this.audio.start();let action=b.dataset.action;this.inputLog.push({action,t:this.sim?.time||0});
 if(action==='hub'){this.audio.stop();this.goto('hub');return;}if(action==='map'){this.goto('map');return;}if(action==='continue'){this.stageId=Math.min(20,this.save.data.cleared+1);this.goto('deck');return;}
 if(action==='stage'){this.stageId=+b.dataset.id;if(this.stageId>this.save.data.cleared+1)return;this.goto('deck');return;}
 if(action==='enemy'){let enemy=E[b.dataset.id];if(enemy)this.toast(enemy.name+' · '+enemy.desc);return;}if(action==='inspect'){this.inspectUnit=b.dataset.id;if(this.unlocked().some(u=>u.id===this.inspectUnit)){if(this.deck.includes(this.inspectUnit))this.deck=this.deck.filter(id=>id!==this.inspectUnit);else if(this.deck.length<MAX_DECK)this.deck.push(this.inspectUnit);else this.toast(L.selectLimit);}let scroll=this.ui.querySelector('.catalog-grid')?.scrollTop||0;this.renderUI();this.ui.querySelector('.catalog-grid').scrollTop=scroll;return;}if(action==='unit'){let id=b.dataset.id;if(!this.unlocked().some(u=>u.id===id))return;this.inspectUnit=id;if(this.deck.includes(id))this.deck=this.deck.filter(x=>x!==id);else if(this.deck.length<MAX_DECK)this.deck.push(id);else this.toast(L.selectLimit);this.renderUI();return;}
 if(action==='start'){if(!this.validDeck())return;this.start();return;}if(action==='restart'){this.start();return;}if(action==='change'){this.goto('deck');return;}if(action==='next'){this.stageId=Math.min(20,this.stageId+1);this.goto('deck');return;}
 if(action==='card'){this.stamp=false;this.selected=this.selected===b.dataset.id?null:b.dataset.id;this.updateHUD();return;}if(action==='stamp'){this.selected=null;this.stamp=!this.stamp;this.updateHUD();return;}if(action==='speed'){this.speed=this.speed===1?2:1;this.updateHUD();return;}if(action==='pause'){this.pause();return;}if(action==='resume'){this.resume();return;}
 if(action==='settings'){this.settingsBack=this.modal;if(['battle','ending','ko','defeat','aftermath'].includes(this.scene)){this.reasons.add('settings');this.sim?.pauses.add('settings');this.audio.pause(true);}this.modal='settings';this.renderUI();return;}
 if(action==='settings-back'){if(this.settingsBack==='pause'){this.modal='pause';}else{this.modal=null;this.reasons.delete('settings');this.sim?.pauses.delete('settings');this.audio.pause(false);}this.save.write();this.renderUI();return;}
 if(action==='mute'){this.save.data.settings.mute=!this.save.data.settings.mute;this.audio.apply();this.save.write();this.renderUI();return;}
 if(action==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen?.();else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>this.toast(L.fullscreenFailed));else this.toast(L.fullscreenUnsupported);return;}
 if(action==='tutorial'){this.deck=['counter','rookie'];this.start(1,{tutorial:true});return;}if(action==='reset'){this.modal='confirm-reset';this.renderUI();return;}if(action==='reset-cancel'){this.modal='settings';this.renderUI();return;}if(action==='reset-confirm'){this.save.reset();this.deck=['counter','rookie'];this.audio.settings=this.save.data.settings;this.audio.apply();this.goto('hub');return;}
 if(action==='skip-interlude'){this.modal=this.scene==='defeat'?'lose':'win';this.scene='battle';this.renderUI();return;}if(action==='skip-event'){this.finishEvent();return;}if(action==='ending'){this.beginEnding();return;}if(action==='skip-ending'){if(this.scene==='ko')this.beginEnding();else this.finishEnding();return;}}
 settingsInput(e){let k=e.target.dataset.setting;if(!k)return;this.save.data.settings[k]=+e.target.value;this.audio.apply();this.save.write();}
 updateTimeline(){let el=this.ui.querySelector('.wave-timeline');if(!el)return;let s=this.sim,groups=new Map();if(this.waveState?.sim!==s)this.waveState={sim:s,marks:new Set(),seen:new Set(),end:1};for(let w of s.waves){if(!groups.has(w.group))groups.set(w.group,w.at);}let marks=[...groups.values()].slice(1);let fresh=s.scheduled.filter(w=>!this.waveState.seen.has(w.at));if(fresh.length)marks.push(Math.min(...fresh.map(w=>w.at)));for(let w of s.scheduled)this.waveState.seen.add(w.at);for(let i=1;i<s.waves.length-1;i++)if(s.waves[i+1].at-s.waves[i].at<=2.3&&s.waves[i].at-s.waves[i-1].at>3)marks.push(s.waves[i].at);for(let t of marks)this.waveState.marks.add(t);marks=[...this.waveState.marks].sort((a,b)=>a-b);let end=this.waveState.end=Math.max(this.waveState.end,...s.waves.map(w=>w.at),...s.scheduled.map(w=>w.at));let p=Math.min(1,s.time/end)*100,next=marks.find(t=>t>s.time);el.querySelector('.wave-fill').style.width=p+'%';el.querySelector('.wave-head').style.left=p+'%';let markerHTML=marks.map(t=>`<i class="wave-flag ${t<=s.time?'passed':''}" style="left:${Math.min(100,t/end*100)}%" title="${Math.ceil(t)}초 웨이브">⚑</i>`).join('');if(this.waveState.html!==markerHTML||!el.querySelector('.wave-markers').innerHTML){el.querySelector('.wave-markers').innerHTML=markerHTML;this.waveState.html=markerHTML;}el.querySelector('.wave-caption').textContent=s.boss?'왕진상 · '+s.bossStage+'페이즈':s.tutorial>=0&&s.tutorial<3?'배치를 마치면 웨이브 시작':next?'다음 웨이브 '+Math.ceil(next-s.time)+'초':s.cursor<s.waves.length?'마지막 웨이브 진행 중':'남은 적을 막아주세요';el.setAttribute('aria-valuenow',Math.round(p));el.setAttribute('aria-valuemin','0');el.setAttribute('aria-valuemax','100');}
 validDeck(){let required=STAGES[this.stageId-1].requiredUnit;return (!required||this.deck.includes(required))&&this.deck.includes('counter')&&this.deck.some(id=>!['counter','staff'].includes(id));}
 pointer(e){if(e.button!==0)return;this.audio.start();let r=this.canvas.getBoundingClientRect(),x=(e.clientX-r.left)*1200/r.width,y=(e.clientY-r.top)*675/r.height;
 if(this.scene==='hub'){let a=this.renderer.hubActors?.find(a=>Math.abs(x-a.x)<60&&y<a.y&&y>a.y-160);if(a){let quotes=L.hubQuotes;this.renderer.hubTap={text:quotes[a.id],x:a.x,y:a.y,until:this.uiTime+2.5};this.audio.sfx('place');}return;}
 if(this.scene!=='battle'||this.modal||this.sim.stopped)return;let hitX=Math.max(30,22*1200/r.width),hitY=Math.max(26,22*675/r.height);let coin=this.sim.coins.filter(c=>!c.collected&&Math.abs(c.x-x)<hitX&&Math.abs(c.y+Math.sin(this.sim.time*3+c.id)*3-y)<hitY).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(coin){this.sim.collect(coin.id);this.consume();this.updateHUD();return;}let col=Math.floor((x-G.x)/G.col),lane=Math.floor((y-G.y)/G.row);if(col>=0&&col<8&&lane>=0&&lane<5){let success=false;let issue=this.stamp?L.emptyRemoval:this.selected?L.placementIssues[this.sim.placementIssue(this.selected,col,lane)]:null;if(this.stamp){success=this.sim.remove(col,lane);if(success)this.stamp=false;}else if(this.selected){success=this.sim.place(this.selected,col,lane);if(success)this.selected=null;}if(!success&&(this.stamp||this.selected)){this.audio.sfx('fail');this.toast(issue||L.invalidPlacement);let p=this.sim.point(col,lane);this.sim.fx('invalid',p.x,p.y-30);}this.inputLog.push({action:'board',x,y,col,lane,success,t:this.sim.time});this.consume();this.updateHUD();}else{this.selected=null;this.stamp=false;this.updateHUD();}}
 consume(){for(let ev of this.sim.drain()){if(ev.type==='sound')this.audio.sfx(ev.name);if(ev.type==='banner')this.banner={text:ev.text,until:this.uiTime+4};if(ev.type==='event'){this.event=ev.kind;this.cineTime=0;this.audio.stop();this.audio.sfx(ev.kind==='sales'||ev.kind==='landlord'?'door':'blast');this.renderUI();}if(ev.type==='result'){this.selected=null;this.stamp=false;if(ev.result==='win'){this.lastSaved=this.save.win(this.sim);if(!this.lastSaved)this.toast(this.save.warning);if(this.stageId===20){this.scene='ko';this.cineTime=0;this.audio.theme('silence');}else{if(this.stageId===19){this.scene='aftermath';this.cineTime=0;}else this.modal='win';this.audio.sfx('win');}}else{this.scene='defeat';this.cineTime=0;this.audio.sfx('blast');}this.renderUI();}}}
 finishEvent(){if(!this.event||this.modal)return;this.event=null;this.cineTime=0;this.sim.dismiss();if(!this.sim.awaiting)this.audio.theme(this.sim.stage.id===20?'boss':'world'+this.sim.stage.world);this.consume();this.renderUI();}
 beginEnding(){this.scene='ending';this.event=null;this.modal=null;this.reasons.clear();this.cineTime=0;this.audio.theme('ending');this.renderUI();}
 finishEnding(){this.save.data.endingSeen=true;this.save.write();this.goto('hub');}
 eventInfo(){let k=this.event,t=this.cineTime;if(k==='sales')return {art:12,name:L.salesName,text:TEXT.sales,duration:3.5};if(k==='landlord')return {art:t<4?13:t<5.7?'rookie':13,name:t<4?L.landlordName:t<5.7?'초보약사':L.landlordName,text:t<4?TEXT.landlord:t<5.7?'…지금요?':'네.',duration:7};if(k==='bossIntro')return {art:10,name:'FINAL NIGHT',text:L.bossAppeared,duration:3};return {art:10,name:L.bossName,text:k==='boss2'?TEXT.boss2:TEXT.boss3,duration:2.6};}
 frame(now){let dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.advance(dt);requestAnimationFrame(t=>this.frame(t));}
 advance(dt){if(!this.reasons.size)this.uiTime+=dt;if(this.scene==='battle'&&this.sim){if(this.event&&!this.reasons.size){this.cineTime+=dt;let info=this.eventInfo();let n=$('#event-text'),sp=$('#event-name'),im=$('#event-art');if(n)n.textContent=info.text;if(sp)sp.textContent=info.name;if(im)im.src=this.thumb(typeof info.art==='string'?info.art:'e'+info.art);if(this.cineTime>=info.duration)this.finishEvent();}else if(!this.modal&&!this.reasons.size){this.accum+=dt*this.speed;while(this.accum>=1/60){this.sim.step(1/60);this.accum-=1/60;this.consume();if(this.sim.stopped){this.accum=0;break;}}}this.updateHUD();}
 if(['ending','ko','defeat','aftermath'].includes(this.scene)&&!this.reasons.size){let before=this.cineTime;this.cineTime+=dt;if(this.scene==='ko'&&before<4&&this.cineTime>=4)this.audio.sfx('blast');if(['defeat','aftermath'].includes(this.scene)&&this.cineTime>=2.5){this.modal=this.scene==='defeat'?'lose':'win';this.scene='battle';this.renderUI();}else if(this.scene==='ko'&&this.cineTime>=9)this.beginEnding();else if(this.scene==='ending'){if(before<12&&this.cineTime>=12)this.audio.sfx('door');if(this.cineTime>=29)this.finishEnding();}this.updateCinematic();}
 this.audio.layer=this.scene==='battle'&&!this.sim?.result?Math.min(1,(this.sim.enemies.filter(z=>z.hp>0).length)/10):0;this.audio.tick();this.renderer.draw(this);}
 updateHUD(){if(this.scene!=='battle')return;let s=this.sim;let money=$('#money');if(money)money.textContent=s.money;for(let el of this.ui.querySelectorAll('.battle-card')){let id=el.dataset.id,cd=s.cooldowns[id]||0;el.classList.toggle('selected',this.selected===id);el.classList.toggle('unavailable',s.money<U[id].cost||cd>.001);let cool=el.querySelector('.cool');cool.style.height=Math.min(100,cd/U[id].cd*100)+'%';el.querySelector('.cool-label').textContent=cd>.1?Math.ceil(cd):'';}let speed=$('[data-action=speed]');if(speed)speed.textContent='×'+this.speed;let stamp=$('[data-action=stamp]');if(stamp)stamp.classList.toggle('selected',this.stamp);let track=$('.progress-track');if(track)track.hidden=!!s.boss;let progress=$('.progress-fill');if(progress)progress.style.width=(s.progress*100)+'%';this.updateTimeline();let tut=$('#tutorial');if(tut){tut.hidden=s.tutorial<0||(s.tutorialCleared&&s.time-s.learnClock>T.openFive+8);tut.textContent=TEXT.tutorial[s.tutorial]||'';}let help=$('#battle-help');if(tut&&this.banner&&this.banner.until>this.uiTime)tut.hidden=true;if(help)help.hidden=!!(this.banner&&this.banner.until>this.uiTime)||!!(tut&&!tut.hidden);if(help)help.textContent=this.stamp?L.removeHint:this.selected?`${U[this.selected].name} · 빈 칸을 터치해 배치`:(s.stage.id<=5&&s.units.some(u=>u.type==='counter')&&!s.units.some(u=>u.type==='rookie')?'판매대 다음은 초보약사! 100을 모아 배치하세요.':L.inputHint);}
 updateCinematic(){let el=$('#cine-content');if(!el)return;let t=this.cineTime;if(this.scene==='ko')el.innerHTML=t<2?`<p>${TEXT.ko}</p>`:t>7?'<h1 class="title">VICTORY</h1>':'';else if(t<9)el.innerHTML='<div class="eyebrow" style="color:#fcebc9">${L.nightFinished}</div>';else if(t<12)el.innerHTML=`<div class="clock">AM ${t<10?'08:59':'09:00'}</div>`;else if(t<17)el.innerHTML=`<p>${TEXT.customer}</p>`;else if(t<24)el.innerHTML='';else el.innerHTML=`<h1 class="title">PHARMACY<br>& JINSANG</h1><div class="eyebrow" style="color:#f1cf91">THE END</div><p style="background:none;color:#e6d7b8;font-size:15px">${TEXT.end}</p>`;}
 renderUI(){let h='',d=this.save.data,s=STAGES[this.stageId-1];if(this.scene==='hub')h=`<div class="screen hub"><div class="hub-top"><div class="eyebrow">${L.hubTag}</div><h1 class="title">PHARMACY<br><span class="brand-plus">&</span> JINSANG</h1><p class="sub">${L.hubDescription}<br>${L.hubDescription2}</p></div><div class="hub-menu"><span class="pill">${d.cleared===20?L.allShifts:`근무 기록 ${d.cleared} / 20`}</span><strong>${d.cleared===20?L.today:L.startQuestion}</strong>${this.btn('continue',d.cleared?L.continue:L.firstShift,'primary')}${this.btn('map',L.schedule)}${d.cleared===20?this.btn('ending',L.replayEnding):''}${this.btn('settings',L.settings,'small')}</div><div class="hub-foot">직원들을 터치해 말을 걸어보세요. · v0.1</div></div>`;
 if(this.scene==='map')h=`<div class="screen"><div class="row between"><div><div class="eyebrow">WORK SCHEDULE</div><h1 class="title">${L.scheduleTitle}</h1></div>${this.btn('hub',L.backHub,'small')}</div><div class="worlds">${WORLDS.map((w,i)=>`<section class="world"><div class="world-title">${w.name}<small>${w.sub}</small></div><div class="stages">${STAGES.filter(s=>s.world===i).map(s=>`<button class="stage ${s.id<=d.cleared?'done':s.id===d.cleared+1?'next':''}" data-action="stage" data-id="${s.id}" ${s.id>d.cleared+1?'disabled':''}>${s.id}<small>${s.id<=d.cleared?L.done:s.id===d.cleared+1?L.workStart:L.waiting}</small></button>`).join('')}</div></section>`).join('')}</div><p class="sub">${L.scheduleHint}</p></div>`;
 if(this.scene==='deck'){this.deck=this.deck.filter(id=>this.unlocked().some(u=>u.id===id));let focus=U[this.inspectUnit]||U[this.deck[0]]||UNITS[0],open=this.unlocked().some(u=>u.id===focus.id);h=`<div class="screen loadout-screen"><header class="row between"><div><div class="eyebrow">${WORLDS[s.world].name} · STAGE ${s.id}</div><h1 class="title">출전 아이템 선택</h1></div>${this.btn('map',L.backSchedule,'small')}</header><div class="loadout-layout"><section class="catalog"><div class="item-detail"><img src="${this.thumb(focus.id)}" alt=""><div><strong>${focus.name}</strong><small>₩ ${focus.cost} · ${focus.role}</small><p>${focus.desc}</p><p class="item-use">${focus.tip}</p>${open?'':`<span class="pill">${focus.unlock}스테이지에서 해금</span>`}</div></div><div class="catalog-grid">${UNITS.map(u=>{let locked=!this.unlocked().some(v=>v.id===u.id);return `<button class="catalog-card ${locked?'locked':''} ${this.deck.includes(u.id)?'chosen':''} ${focus.id===u.id?'focused':''}" data-action="inspect" data-id="${u.id}" aria-label="${u.name}${locked?' 잠김':''}" aria-pressed="${this.deck.includes(u.id)}"><img src="${this.thumb(u.id)}" alt=""><b>${locked?'🔒 '+u.unlock+'단계':u.short}</b><small>${locked?'미해금':'₩ '+u.cost}</small>${this.deck.includes(u.id)?'<em>✓</em>':''}</button>`}).join('')}</div></section><aside class="loadout-aside"><strong>출전 ${this.deck.length} / ${MAX_DECK}</strong><div class="loadout-slots">${Array.from({length:MAX_DECK},(_,i)=>{let u=U[this.deck[i]];return u?`<button data-action="unit" data-id="${u.id}" aria-label="${u.name} 출전 제외"><img src="${this.thumb(u.id)}" alt=""><span>${u.short}</span></button>`:`<div class="empty-slot">${i+1}</div>`}).join('')}</div><small>카드를 한 번 누르면 추가, 다시 누르면 제외<br>출전 슬롯을 눌러도 제외됩니다.</small><div class="visitors"><b>이번 근무의 방문자</b>${s.requiredUnit?`<div class="required-enemy">필수 준비: ${U[s.requiredUnit].name}</div>`:''}<div class="enemy-preview">${s.types.map(id=>`<button class="enemy-detail" data-action="enemy" data-id="${id}" aria-label="${E[id].name}"><img alt="" src="${this.thumb(id==='armored'?'armored':'e'+E[id].art)}"><span><b>${E[id].name}</b><small>${E[id].desc}</small>${E[id].counter?`<strong>${E[id].counter}</strong>`:''}</span></button>`).join('')}</div></div><p class="loadout-hint">${s.hint}</p>${this.btn('start',L.start,'primary',this.validDeck()?'':'disabled')}</aside></div></div>`;}
 if(['battle','defeat','aftermath'].includes(this.scene)){h=`<div class="hud"><div class="money-box"><small>${L.money}</small><strong id="money">${this.sim.money}</strong></div><div class="battle-cards">${this.sim.deck.map(id=>`<button class="battle-card" data-action="card" data-id="${id}" aria-label="${U[id].name} 비용 ${U[id].cost}"><img src="${this.thumb(id)}" alt=""><b>${U[id].short}</b><span class="cost">₩ ${U[id].cost}</span><span class="cool"></span><span class="cool-label"></span></button>`).join('')}</div><div class="hud-tools"><button data-action="speed">×${this.speed}</button><button data-action="pause" aria-label="${L.pause}">Ⅱ</button><button class="stamp" data-action="stamp">${L.stamp}</button></div></div><div class="battle-info"><span>${WORLDS[this.sim.stage.world].name} · ${this.stageId} ${this.sim.stage.title}</span><span>${L.defend}</span></div><div class="wave-timeline" role="progressbar" aria-label="웨이브 진행"><div class="wave-caption"></div><div class="wave-rail"><div class="wave-fill"></div><div class="wave-markers"></div><span class="wave-head">●</span></div></div><div id="tutorial" class="tutorial"></div><div class="battle-help" id="battle-help"></div>`;if(this.event){let info=this.eventInfo();h+=`<div class="event-banner"><img id="event-art" src="${this.thumb(typeof info.art==='string'?info.art:'e'+info.art)}" alt=""><div class="speech"><small id="event-name">${info.name}</small><span id="event-text">${info.text}</span></div>${this.btn('skip-event',L.skip,'small')}</div>`;}}
 if(['defeat','aftermath'].includes(this.scene))h+=`<button class="skip" data-action="skip-interlude">${L.skip}</button>`;if(this.scene==='ending'||this.scene==='ko')h=`<div class="ending-caption" id="cine-content"></div><button class="skip" data-action="skip-ending">${L.skip}</button><button class="skip" style="top:3%;bottom:auto" data-action="pause">Ⅱ 일시정지</button>`;
 if(this.modal){let body='';if(this.modal==='pause')body=`<div class="eyebrow">TAKE A BREATH</div><h1 class="title">${L.rest}</h1><p class="sub">${L.paused}</p><div class="modal-actions">${this.btn('resume',L.resume,'primary')}${this.scene==='battle'?this.btn('restart',L.restart):''}${this.btn('settings',L.settings)}${this.btn('map',L.chooseStage)}</div>`;
 if(this.modal==='win'){let next=UNITS.filter(u=>u.unlock===this.stageId+1);body=`<div class="eyebrow">SHIFT COMPLETE</div><h1 class="title">${TEXT.win}</h1><p class="sub">${Math.floor(this.sim.time/60)}분 ${Math.floor(this.sim.time%60)}초 · 112 출동 ${this.sim.stats.police}회<br>${this.lastSaved?L.saved:L.saveFailed}</p>${next.map(u=>`<div class="unlock-card"><img src="${this.thumb(u.id)}" alt=""><div><b>${u.name} · ${u.role}</b><p>${u.desc}</p></div></div>`).join('')}${STAGES[this.stageId]?`<p class="next-preview"><b>${L.nextShift} · ${STAGES[this.stageId].title}</b><br>${STAGES[this.stageId].hint}</p>`:''}${this.stageId===7?'<p>새 근무지가 열렸습니다 — 병원 앞 약국</p>':this.stageId===15?'<p>심야 운영을 시작합니다.</p>':this.stageId===19?'<p>쿵.　쿵.　쿵.<br>…바깥에 누가 있는 걸까요?</p>':''}<div class="modal-actions">${this.btn('next',L.next,'primary')}${this.btn('restart',L.sameAgain)}${this.btn('hub',L.toHub)}</div>`;}
 if(this.modal==='lose')body=`<div class="eyebrow">CLOSED FOR TODAY</div><h1 class="title">${TEXT.lose}</h1><p class="sub">${L.breachLane}: ${L.fromTop} ${(this.sim.breachedLane??0)+1}${L.laneUnit}<br>${L.lossHint}<br>${this.sim.units.some(u=>u.lane===this.sim.breachedLane&&U[u.type].damage>0)?L.defenseTip:L.noAttacker}</p><div class="modal-actions">${this.btn('restart',L.retry,'primary')}${this.btn('change',L.changeUnits)}${this.btn('map',L.chooseStage)}</div>`;
 if(this.modal==='settings')body=`<div class="eyebrow">PHARMACY SETTINGS</div><h1 class="title">${L.settingsTitle}</h1>${[['master',L.master],['bgm',L.bgm],['sfx',L.sfx]].map(([k,t])=>`<label>${t}<input aria-label="${t}" data-setting="${k}" type="range" min="0" max="1" step=".01" value="${d.settings[k]}"></label>`).join('')}<div class="row">${this.btn('mute',d.settings.mute?L.soundOn:L.mute,'small')}${this.btn('fullscreen',L.fullscreen,'small')}</div><div class="modal-actions">${this.btn('tutorial',L.replayTutorial,'small')}${this.btn('reset',L.reset,'small')}${this.btn('settings-back',L.back,'primary')}</div>`;
 if(this.modal==='confirm-reset')body=`<h1 class="title">${L.eraseTitle}</h1><p class="sub">${L.eraseBody}<br>${L.eraseWarning}</p><div class="modal-actions">${this.btn('reset-cancel',L.back,'primary')}${this.btn('reset-confirm',L.eraseAll)}</div>`;
 h+=`<div class="modal-wrap"><div class="modal">${body}</div></div>`;}
 this.ui.innerHTML=h;this.updateHUD();this.updateCinematic();}
}
const app=new App();await app.init();if(query.has('dev'))window.__game={app,Simulation,UNITS,ENEMIES,STAGES,U,E,BOARD:G};
