const SCALE=[0,2,3,5,7,9,10,12],MELODY=[0,4,2,6,4,2,1,3,0,2,4,7,6,4,3,1,0,0,3,5,4,2,6,4,1,3,5,7,4,3,1,0];
export class AudioManager{
 constructor(settings){this.settings=settings;this.nodes=new Set();this.mode='hub';this.layer=0;this.step=0;this.next=0;this.blocked=false;this.last={};}
 start(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.effects=this.ctx.createGain();this.music.connect(this.master);this.effects.connect(this.master);this.master.connect(this.ctx.destination);this.apply();}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});this.next=Math.max(this.next,this.ctx.currentTime+.05);}
 apply(){if(!this.ctx)return;let t=this.ctx.currentTime;this.master.gain.setTargetAtTime(this.settings.mute?0:this.settings.master,t,.03);this.music.gain.setTargetAtTime(this.settings.bgm*.15,t,.06);this.effects.gain.setTargetAtTime(this.settings.sfx*.26,t,.03);}
 tone(freq,at,len,vol=.3,wave='sine',music=false,to=null){if(!this.ctx||this.nodes.size>(music?35:24))return;let o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=wave;o.frequency.setValueAtTime(freq,at);if(to)o.frequency.exponentialRampToValueAtTime(to,at+len);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(Math.max(.001,vol),at+.01);g.gain.exponentialRampToValueAtTime(.0001,at+len);o.connect(g);g.connect(music?this.music:this.effects);o.start(at);o.stop(at+len+.02);this.nodes.add(o);o.onended=()=>{o.disconnect();g.disconnect();this.nodes.delete(o);};}
 stop(){if(!this.ctx)return;for(let o of this.nodes){try{o.stop();}catch{}}this.nodes.clear();this.next=this.ctx.currentTime+.08;}
 pause(on){this.blocked=on;if(on)this.stop();else if(this.ctx)this.next=this.ctx.currentTime+.05;}
 theme(mode){if(mode!==this.mode){this.stop();this.mode=mode;this.step=0;}this.blocked=false;}
 tick(){if(!this.ctx||this.blocked||this.mode==='silence'||this.ctx.state!=='running')return;if(this.next<this.ctx.currentTime)this.next=this.ctx.currentTime+.02;let bpm={hub:90,world0:108,world1:122,world2:96,boss:138,ending:82}[this.mode]||100,beat=60/bpm/2;while(this.next<this.ctx.currentTime+.12){let i=this.step++,t=this.next,root=this.mode==='world2'||this.mode==='boss'?146.83:174.61,degree=MELODY[i%32],chord=[0,5,3,7][Math.floor(i/32)%4],f=root*Math.pow(2,SCALE[degree]/12);if(i%2===0||this.mode==='world1')this.tone(f,t,beat*.75,.28,this.mode==='world2'?'sine':'triangle',true);if(i%4===0)this.tone(root/2*Math.pow(2,chord/12),t,beat*2,.48,'triangle',true);if(this.layer&&i%2===0)this.tone(i%4===0?95:220,t,.055,.28*this.layer,'triangle',true,40);this.next+=beat;if(this.next<this.ctx.currentTime-1)this.next=this.ctx.currentTime;}}
 sfx(name){if(!this.ctx||this.blocked)return;let t=this.ctx.currentTime;if(t-(this.last[name]??-9)<(name==='hurt'||name==='shoot'?.07:.03))return;this.last[name]=t;let pitch=1+(Math.random()-.5)*.08;let data={mortar:[170,65,.22],spray:[1100,430,.18],freeze:[1500,2400,.35],capsule:[850,440,.045],bag:[270,100,.22],place:[440,800,.13],remove:[380,140,.15],coin:[980,1500,.12],shoot:[700,350,.06],syrup:[360,180,.2],roll:[170,220,.13],hurt:[110,70,.09],down:[180,60,.18],break:[280,70,.14],blast:[140,35,.4],door:[880,660,.3],fail:[180,140,.1]};if(name==='police'){for(let i=0;i<4;i++)this.tone(i%2?620:870,t+i*.19,.22,.4,'triangle');return;}if(name==='win'){[440,554,659,880].forEach((f,i)=>this.tone(f,t+i*.09,.45,.3,'triangle'));return;}let [a,b,c]=data[name]||data.shoot;this.tone(a*pitch,t,c,.4,'triangle',false,b);}
}
