import {score} from './music.js?v=33';
import {MusicRack} from './instruments.js?v=33';
export class AudioManager{
 constructor(settings){this.settings=settings;this.nodes=new Set();this.mode='hub';this.layer=0;this.step=0;this.next=0;this.blocked=false;this.last={};}
 start(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.effects=this.ctx.createGain();this.music.connect(this.master);this.effects.connect(this.master);this.compressor=this.ctx.createDynamicsCompressor();this.compressor.threshold.value=-12;this.compressor.knee.value=12;this.compressor.ratio.value=4;this.compressor.attack.value=.006;this.compressor.release.value=.18;this.master.connect(this.compressor);this.compressor.connect(this.ctx.destination);this.rack=new MusicRack(this.ctx,this.music);this.apply();}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});this.next=Math.max(this.next,this.ctx.currentTime+.05);}
 apply(){if(!this.ctx)return;let t=this.ctx.currentTime;this.master.gain.setTargetAtTime(this.settings.mute?0:this.settings.master,t,.03);this.music.gain.setTargetAtTime(this.settings.bgm*.75,t,.06);this.effects.gain.setTargetAtTime(this.settings.sfx*.26,t,.03);}
 tone(freq,at,len,vol=.3,wave='sine',music=false,to=null){if(!this.ctx||this.nodes.size>(music?35:24))return;let o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=wave;o.frequency.setValueAtTime(freq,at);if(to)o.frequency.exponentialRampToValueAtTime(to,at+len);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(Math.max(.001,vol),at+.01);g.gain.exponentialRampToValueAtTime(.0001,at+len);o.connect(g);g.connect(music?this.music:this.effects);o.start(at);o.stop(at+len+.02);this.nodes.add(o);o.onended=()=>{o.disconnect();g.disconnect();this.nodes.delete(o);};}
 stop(){if(!this.ctx)return;this.rack?.stop();for(let o of this.nodes){try{o.stop();}catch{}}this.nodes.clear();this.next=this.ctx.currentTime+.08;}
 pause(on){this.blocked=on;if(on){this.stop();if(this.ctx)this.music.gain.setTargetAtTime(0,this.ctx.currentTime,.02);}else if(this.ctx){this.next=this.ctx.currentTime+.05;this.apply();}}
 theme(mode){if(mode!==this.mode){this.stop();this.mode=mode;this.step=0;this.mix=0;}this.blocked=false;this.apply();}
 tick(){if(!this.ctx||this.blocked||this.mode==='silence'||this.ctx.state!=='running')return;if(this.next<this.ctx.currentTime)this.next=this.ctx.currentTime+.02;while(this.next<this.ctx.currentTime+.12){this.mix=(this.mix||0)+((this.layer||0)-(this.mix||0))*.15;let part=score(this.mode,this.step++,this.mix);for(let n of part.notes)this.rack.play(n,this.next+(n.delay||0));this.next+=part.beat;}}
 sfx(name){if(!this.ctx||this.blocked)return;let t=this.ctx.currentTime;if(t-(this.last[name]??-9)<(name==='impact'?.12:name==='hurt'||name==='shoot'?.07:.03))return;this.last[name]=t;let pitch=1+(Math.random()-.5)*.08;let data={impact:[420,160,.045],mortar:[170,65,.22],spray:[1100,430,.18],freeze:[1500,2400,.35],capsule:[850,440,.045],bag:[270,100,.22],place:[440,800,.13],remove:[380,140,.15],coin:[980,1500,.12],shoot:[700,350,.06],syrup:[360,180,.2],roll:[170,220,.13],hurt:[110,70,.09],down:[180,60,.18],break:[280,70,.14],blast:[140,35,.4],door:[880,660,.3],fail:[180,140,.1]};if(name==='wave'){[440,554,740].forEach((f,i)=>this.tone(f,t+i*.14,.18,.22,'triangle'));return;}if(name==='police'){for(let i=0;i<4;i++)this.tone(i%2?620:870,t+i*.19,.22,.4,'triangle');return;}if(name==='win'){[440,554,659,880].forEach((f,i)=>this.tone(f,t+i*.09,.45,.3,'triangle'));return;}let [a,b,c]=data[name]||data.shoot;this.tone(a*pitch,t,c,name==='impact'?.12:.4,'triangle',false,b);}
}
