// Original synthesized instruments. No downloaded samples or soundfonts.
const PATCHES={
 marimba:{harmonics:[1,.16,.07,.045],attack:.005,release:.18,cutoff:4200,pan:-.16},
 celesta:{harmonics:[1,.04,.28,.015,.11],attack:.006,release:.65,cutoff:7800,pan:.28},
 pizz:{harmonics:[1,.44,.2,.13,.06],attack:.004,release:.12,cutoff:2500,pan:-.38},
 bass:{harmonics:[1,.28,.1],attack:.012,release:.1,cutoff:780,pan:0},
 reed:{harmonics:[1,.08,.24,.03,.09],attack:.035,release:.14,cutoff:2400,pan:.12},
 pad:{harmonics:[1,.2,.08,.03],attack:.16,release:.6,cutoff:1400,pan:-.22}
};
export class MusicRack {
 constructor(ctx,output,{offline=false}={}){this.ctx=ctx;this.offline=offline;this.voices=new Set();this.waves={};this.input=ctx.createGain();this.dry=ctx.createGain();this.dry.gain.value=.86;this.input.connect(this.dry);this.dry.connect(output);this.convolver=ctx.createConvolver();const impulse=ctx.createBuffer(2,Math.floor(ctx.sampleRate*.85),ctx.sampleRate);let seed=417;for(let ch=0;ch<2;ch++){let d=impulse.getChannelData(ch);for(let i=0;i<d.length;i++){seed=(seed*1664525+1013904223)>>>0;d[i]=(seed/4294967296*2-1)*Math.pow(1-i/d.length,3)*.35;}}this.convolver.buffer=impulse;this.wet=ctx.createGain();this.wet.gain.value=.18;this.input.connect(this.convolver);this.convolver.connect(this.wet);this.wet.connect(output);this.noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);let n=this.noise.getChannelData(0);for(let i=0;i<n.length;i++){seed=(seed*1664525+1013904223)>>>0;n[i]=(seed/4294967296*2-1)*.7;}}
 play(note,at){const c=this.ctx;if(!this.offline&&this.voices.size>=48)return;let inst=note.instrument||'marimba',p=PATCHES[inst]||PATCHES.marimba,duration=note.duration,amp=note.volume,source,filter=c.createBiquadFilter(),gain=c.createGain(),pan=c.createStereoPanner();pan.pan.value=note.pan??p.pan;filter.type='lowpass';filter.Q.value=.5;let release=p.release,attack=p.attack;
 if(inst==='brush'||inst==='hat'){source=c.createBufferSource();source.buffer=this.noise;filter.type='bandpass';filter.frequency.value=inst==='brush'?1700:7000;filter.Q.value=.7;release=.045;attack=.003;}else{source=c.createOscillator();if(inst==='kick'){source.type='sine';source.frequency.setValueAtTime(110,at);source.frequency.exponentialRampToValueAtTime(46,at+.09);filter.frequency.value=400;release=.08;attack=.004;}else{if(!this.waves[inst]){let real=new Float32Array(p.harmonics.length+1),imag=new Float32Array(p.harmonics.length+1);p.harmonics.forEach((v,i)=>imag[i+1]=v);this.waves[inst]=c.createPeriodicWave(real,imag);}source.setPeriodicWave(this.waves[inst]);source.frequency.setValueAtTime(note.frequency,at);filter.frequency.setValueAtTime(p.cutoff,at);if(inst!=='pad'&&inst!=='reed')filter.frequency.exponentialRampToValueAtTime(Math.max(300,p.cutoff*.42),at+duration);}}
 const end=at+duration+release;gain.gain.setValueAtTime(.00001,at);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,amp),at+attack);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,amp*(inst==='pad'?.55:.25)),at+Math.max(attack+.01,duration));gain.gain.exponentialRampToValueAtTime(.00001,end);source.connect(filter);filter.connect(gain);gain.connect(pan);pan.connect(this.input);source.start(at);source.stop(end+.02);let voice={source,gain,end};this.voices.add(voice);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();pan.disconnect();this.voices.delete(voice);};}
 stop(){let t=this.ctx.currentTime;for(let v of this.voices){try{v.gain.gain.cancelScheduledValues(t);v.gain.gain.setTargetAtTime(.00001,t,.008);v.source.stop(t+.03);}catch{}}this.voices.clear();}
}
