// UI copy is kept outside the simulation. Add another locale module with this shape.
export const L={
 danger:'돌파 주의',policeSpent:'출동 소진',breachLane:'돌파된 레인',fromTop:'위에서',laneUnit:'번째 줄',noAttacker:'이 레인에 적을 공격할 유닛이 없었어요. 공격 유닛을 먼저 확보해보세요.',defenseTip:'적이 앞쪽 방어선을 넘기 전에 화력을 보강하거나 직원으로 막아보세요.',
 newUnit:'이번 근무부터',nextShift:'다음 근무',enemyHint:'손님 그림을 눌러 특징을 확인하세요.',
 incoming:'접근',emptyRemoval:'퇴근시킬 유닛이 없는 칸이에요.',placementIssues:{paused:'일시정지를 해제해주세요.',selection:'먼저 출전 카드를 골라주세요.',closed:'아직 열리지 않은 레인이에요.',occupied:'이미 유닛이 있는 칸이에요.',money:'돈이 부족해요. ₩ 아이콘을 모아주세요.',cooldown:'카드가 준비 중이에요. 남은 초를 확인해주세요.'},
 loading:'약국 문을 여는 중…',loadingHint:'오늘도 무사히 영업할 수 있을까요?',loadError:'게임을 열지 못했어요',reload:'다시 열기',
 selectLimit:'출전 유닛은 최대 9종이에요.',fullscreenUnsupported:'이 브라우저는 전체화면을 지원하지 않아요.',fullscreenFailed:'이 브라우저에서는 전체화면을 열 수 없어요.',invalidPlacement:'빈 칸, 돈, 카드 준비시간을 확인해주세요.',
 hubTag:'A VERY ORDINARY PHARMACY · 아주 평범한 약국',hubDescription:'조제하고, 버티고, 오늘도 영업합니다.',hubDescription2:'다섯 레인 너머에서 누군가 오고 있어요.',allShifts:'모든 근무 완료',today:'오늘도 영업합니다.',startQuestion:'오늘의 근무를 시작할까요?',continue:'이어서 근무하기 →',firstShift:'첫 근무 시작 →',schedule:'근무표 보기',settings:'설정',replayEnding:'엔딩 다시 보기',hubHint:'직원들을 터치해 말을 걸어보세요.',backHub:'← 약국으로',scheduleTitle:'오늘의 근무표',scheduleHint:'강화도, 재화 노가다도 없습니다. 다음 근무를 여는 건 여러분의 전략이에요.',done:'완료 ✓',workStart:'근무 시작',waiting:'대기',backSchedule:'← 근무표',preparation:'오늘의 준비',visitors:'등장하는 손님들',deckHint:'판매대와 공격 유닛을 포함해주세요.',resetHint:'112는 근무당 한 번, 전장의 적을 모두 연행합니다.',start:'근무 시작 →',money:'전투 자금 ₩',stamp:'퇴근 도장',pause:'일시정지',defend:'마지막 손님까지 지켜주세요',skip:'건너뛰기',rest:'잠깐, 쉬어가요.',paused:'전투와 모든 타이머가 멈췄어요.',resume:'계속하기',restart:'다시하기',chooseStage:'스테이지 선택',next:'다음 근무 →',sameAgain:'같은 근무 다시 도전',toHub:'약국으로',retry:'다시 도전',changeUnits:'유닛 변경',settingsTitle:'약국 설정',master:'전체 음량',bgm:'배경 음악',sfx:'효과음',soundOn:'소리 켜기',mute:'음소거',fullscreen:'전체화면',replayTutorial:'튜토리얼 다시 보기',reset:'데이터 초기화',back:'돌아가기',eraseTitle:'기록을 지울까요?',eraseBody:'클리어·해금·설정이 모두 초기화됩니다.',eraseWarning:'이 동작은 되돌릴 수 없어요.',eraseAll:'모든 기록 초기화',removeHint:'퇴근시킬 유닛을 터치하세요',inputHint:'돈 터치 → 카드 선택 → 빈 칸 배치',saved:'진행도와 근무 기록을 저장했어요.',saveFailed:'진행 저장에 실패했습니다. 페이지를 닫기 전에 확인해주세요.',
 lossHint:'약국 전체 1회의 긴급출동을 이미 사용했어요.',lossStrategy:'직원과 시럽으로 시간을 벌어보세요.',nightFinished:'길었던 밤이 지나고',bossAppeared:'왕진상 좀비가 나타났습니다!',salesName:'제약회사 영업사원',landlordName:'건물주',bossName:'왕진상 좀비',
 hubQuotes:{rookie:'오늘은 좀 조용하겠지…?',staff:'진열은 제가 할게요!',temp:'저, 퇴근 시간은요?',veteran:'두 번 설명할 시간에 두 번 쏩니다.',director:'오늘도 잘 부탁합니다.'}
};
