import {Simulation} from './sim.js?v=34';import {UNITS,U,BALANCE,STAGES,makeWaves} from './data.js?v=34';
export function runRules(){let results=[];let check=(name,f)=>{try{f();results.push({name,status:'pass'});}catch(e){results.push({name,status:'fail',detail:e.message});}};let assert=(x,m='assertion failed')=>{if(!x)throw Error(m);};let newSim=(deck=['counter','rookie'])=>{let s=new Simulation(2,deck,23,{tutorial:false});s.money=250;return s;};let tick=(s,t)=>{for(let i=0;i<Math.ceil(t*60);i++)s.step(1/60);};
 check('0자금 하늘돈 수집·낙하·일시정지',()=>{let s=new Simulation(2,['counter','rookie']);assert(s.money===0);tick(s,3.2);assert(s.coins.length===2&&s.money===0);let y=s.coins[0].y;s.pauses.add('test');tick(s,1);assert(s.coins[0].y===y);s.pauses.clear();for(let c of s.coins)s.collect(c.id);assert(s.money===50&&s.place('counter',0,2));});
 check('모든 전투 레인 등장 보장 1900시드',()=>{for(let stage of STAGES.slice(1))for(let seed=0;seed<100;seed++)assert(new Set(makeWaves(stage,seed).map(w=>w.lane)).size===5,'stage '+stage.id+' seed '+seed);});
 check('포장갑옷은 돌돌이로 해제 후 일반 피해',()=>{let s=newSim(['roller']);let z=s.spawn('armored',2,600);s.damage(z,450,'temp');assert(z.hp===240&&z.shield===60);s.damage(z,U.roller.damage,'roller');assert(z.shield===30);s.damage(z,U.roller.damage,'roller');assert(z.shield===0&&z.hp===240);s.damage(z,20,'rookie');assert(z.hp===220);});
 check('포장갑옷 소개 단계 수와 간격',()=>{for(let id of [9,10,12,18])for(let seed=0;seed<50;seed++){let ws=makeWaves(STAGES[id-1],seed),armor=ws.filter(w=>w.type==='armored');assert(armor.length>0&&armor.length<=(id===9?2:id===10?3:4));for(let i=1;i<armor.length;i++)assert(armor[i].at-armor[i-1].at>=14);}});
 check('12단계 마지막 무리 앞 생성 공백12초',()=>{let ws=makeWaves(STAGES[11],1),last=Math.max(...ws.map(w=>w.group));let before=Math.max(...ws.filter(w=>w.group===last-1).map(w=>w.at)),next=Math.min(...ws.filter(w=>w.group===last).map(w=>w.at));assert(Math.abs(next-before-12)<.01);});
 check('돈 수동 수집·중복 획득 방지',()=>{let s=newSim();s.place('counter',0,2);tick(s,3.1);assert(s.money===250-U.counter.cost);let c=s.coins[0];assert(c);assert(s.collect(c.id));assert(!s.collect(c.id));assert(s.money===250-U.counter.cost+25);});
 check('자금 부족·점유 칸은 차감하지 않음',()=>{let s=newSim();assert(s.place('rookie',0,2));let m=s.money;assert(!s.place('counter',0,2));assert(s.money===m);s.money=0;assert(!s.place('rookie',1,2));});
 check('카드 쿨다운은 재배치와 분리',()=>{let s=newSim();s.place('rookie',0,2);s.remove(0,2);assert(!s.place('rookie',1,2));assert(s.money===250-U.rookie.cost);});
 check('닫힌 레인·튜토리얼 직접 행동',()=>{let s=new Simulation(1,['counter','rookie']);s.money=250;assert(!s.place('counter',0,0));s.place('counter',0,2);assert(s.tutorial===1);tick(s,3.1);s.collect(s.coins.find(c=>!c.sky).id);assert(s.tutorial===2);s.place('rookie',1,2);assert(s.activeLanes.length===3);tick(s,36);assert(s.activeLanes.length===5);});
 check('퇴근 도장 생성·공격 예약 제거',()=>{let s=newSim();s.place('counter',0,2);s.remove(0,2);tick(s,4);assert(s.coins.filter(c=>!c.sky).length===0&&s.units.length===0);});
 check('초보약사 발사와 실제 피해',()=>{let s=newSim();s.place('rookie',1,2);let z=s.spawn('normal',2,430);tick(s,1.1);assert(z.hp===180);});
 check('베테랑 2연사 실제 두 발',()=>{let s=newSim(['veteran']);s.money=200;s.place('veteran',1,2);let z=s.spawn('normal',2,420);tick(s,1.15);assert(z.hp===200-2*U.veteran.damage,'two shots damage: '+z.hp);assert(s.stats.shots===2);});
 check('직원은 무공격 탱커',()=>{let s=newSim(['staff']);s.place('staff',1,2);let z=s.spawn('normal',2,360);let x=z.x;tick(s,3);assert(z.hp===200&&z.x===x);assert(s.units[0].hp<1200&&s.stats.shots===0);});
 check('알바 준비 전 제거는 피해 없음',()=>{let s=newSim(['temp']);s.place('temp',2,2);let z=s.spawn('normal',2,450);tick(s,1);s.remove(2,2);tick(s,2);assert(z.hp===200);});
 check('알바 준비 이후 1회 범위 공격',()=>{let s=newSim(['temp']);s.place('temp',2,2);let z=s.spawn('bulky',2,485);let z2=s.spawn('bulky',1,485);tick(s,3.3);assert(z.hp===350&&z2.hp===350);assert(s.units.length===0&&s.stats.shots===1);assert(s.cooldowns.temp>30);});
 check('시럽 감속과 시간 해제',()=>{let s=newSim(['syrup']);s.place('syrup',1,2);let z=s.spawn('delivery',2,470);tick(s,1.4);assert(z.hp===140&&z.slow>0);s.remove(1,2);tick(s,3.1);assert(z.slow===0);});
 check('돌돌이 한 발 최대2마리·중복 피해 없음',()=>{let s=newSim(['roller']);s.place('roller',1,2);let a=s.spawn('bulky',2,435),b=s.spawn('bulky',2,495),c=s.spawn('bulky',2,555);tick(s,1.8);assert(s.stats.shots===1);assert(a.hp===800-U.roller.damage&&b.hp===800-U.roller.damage&&c.hp===800);});
 for(let lane of [0,2,4])check('자동조제 유효 레인 '+lane,()=>{let s=newSim(['dispenser']);s.place('dispenser',1,lane);let zs=[0,1,2,3,4].map(l=>s.spawn('normal',l,440));tick(s,1.3);for(let z of zs)assert(z.hp===(Math.abs(z.lane-lane)<=1?188:200));});
 check('연고칼 사거리 제한',()=>{let s=newSim(['spatula']);s.place('spatula',2,2);let near=s.spawn('bulky',2,470),far=s.spawn('bulky',2,750);tick(s,.7);assert(near.hp===755&&far.hp===800);});
 check('장바구니 선파괴·초과 피해',()=>{let s=newSim(),z=s.spawn('basket',2,600);s.damage(z,200);assert(z.shield===0&&z.hp===150);});
 check('감기구름 아군 공격속도 상태',()=>{let s=newSim();s.place('rookie',1,2);let z=s.spawn('cold',2,480);z.ability=.1;tick(s,.2);assert(s.units[0].cloud>0);});
 check('진상 방해·대사·재적용 저항',()=>{let s=newSim();s.place('rookie',1,2);let z=s.spawn('complaint',2,470);z.ability=.1;tick(s,.2);assert(s.units[0].jam>0&&z.quote.length>0);let resisted=s.units[0].resist;assert(resisted>0);});
 check('스마트폰 가속 예고',()=>{let s=newSim(),z=s.spawn('phone',2,790);tick(s,.1);assert(z.phone&&z.speech>0);});
 check('일시정지 전체 상태 불변',()=>{let s=newSim();s.place('counter',0,2);s.spawn('normal',2,500);tick(s,1);s.pauses.add('manual');let before=JSON.stringify(s.snapshot());tick(s,20);assert(JSON.stringify(s.snapshot())===before);});
 check('112 전장 전체 단 한 번 연행·다른 레인 재돌파 패배',()=>{let s=newSim();for(let l=0;l<5;l++)s.spawn(l===2?'complaint':'normal',l,l===0?136:600);tick(s,.1);assert(s.policeUsed&&s.stats.police===1&&s.enemies.length===0&&s.arrest.people.length===5);let t=s.arrest.elapsed;s.pauses.add('manual');tick(s,2);assert(s.arrest.elapsed===t);s.pauses.clear();tick(s,4.9);assert(!s.arrest);s.spawn('normal',4,136);tick(s,.1);assert(s.result==='lose'&&s.breachedLane===4);});
 check('연행은 미래 웨이브를 삭제하지 않음',()=>{let s=newSim();let left=s.waves.length;s.spawn('normal',0,136);tick(s,5);assert(s.waves.length===left&&!s.callPolice()&&s.stats.police===1);tick(s,s.waves[0].at-s.time+1);assert(s.enemies.length>0);});
 check('왕진상 경찰 제압·HP와 페이즈 유지·재돌파 패배',()=>{let s=new Simulation(20,['rookie']);s.bossStarted=true;s.bossStage=2;let b=s.spawn('boss',2,136);b.hp=2000;s.spawn('normal',1,500);tick(s,.1);assert(s.arrest.boss&&s.arrest.people.length===1&&!s.result);let t=s.arrest.elapsed;s.pauses.add('manual');tick(s,1);assert(s.arrest.elapsed===t);s.pauses.clear();tick(s,4.9);assert(!s.result&&!s.arrest&&s.boss.hp===2000&&s.bossStage===2&&s.boss.x>1050);assert(!s.stats.killed.boss&&s.stats.killed.normal===1&&!s.callPolice());s.boss.x=136;tick(s,.1);assert(s.result==='lose');});
 check('보스 65%·30% 페이즈 정확히 한 번',()=>{let s=new Simulation(20,['rookie']);s.bossStarted=true;s.bossStage=1;let z=s.spawn('boss',2,900);s.damage(z,1800);assert(s.awaiting==='boss2');s.dismiss();assert(z.lane===1);s.damage(z,1800);assert(s.awaiting==='boss3');s.dismiss();s.damage(z,1400);assert(s.result==='win'&&s.bossStage===3);});
 check('보스 큰 피해에서도 필수 페이즈 보존',()=>{let s=new Simulation(20,['rookie']);s.bossStarted=true;s.bossStage=1;let z=s.spawn('boss',2,900);s.damage(z,9999);assert(s.awaiting==='boss2');s.dismiss();assert(s.awaiting==='boss3');s.dismiss();assert(s.result==='win');});
 check('Stage 10 쿨다운 혼선·돈 보존',()=>{let s=new Simulation(10,['rookie']);s.money=100;s.place('rookie',1,2);let m=s.money,cd=s.cooldowns.rookie;s.awaiting='sales';s.dismiss();assert(s.money===m&&s.cooldowns.rookie===cd+2);});
 check('Stage 19 강탈 없음·후속 웨이브',()=>{let s=new Simulation(19,['rookie']);let m=s.money;s.awaiting='landlord';s.dismiss();assert(s.money===m&&s.scheduled.length===12);});
 check('20스테이지 데이터·ID·레인·해금 순서',()=>{assert(STAGES.length===20);for(let s of STAGES){let ws=makeWaves(s,s.id*1979);if(s.id>1)assert(ws.length>0);for(let w of ws){assert(w.at>=0&&w.lane>=0&&w.lane<5);assert(s.types.includes(w.type));}}assert(UNITS.length===14&&UNITS.filter(u=>u.unlock===17).length===1);});
 check('재시작 돈·경찰·타이머 독립',()=>{let s=newSim();s.place('rookie',1,2);s.police[2].used=true;let n=newSim();assert(n.time===0&&n.money===250&&!n.police[2].used&&n.units.length===0);});
 check('튜토리얼 적 전멸 후 불필요한 종료 대기 없음',()=>{let s=new Simulation(1,['counter','rookie']);s.money=250;s.place('counter',0,2);tick(s,3.1);s.collect(s.coins.find(c=>!c.sky).id);s.place('rookie',1,2);for(let i=0;i<6000&&!s.result;i++){for(let z of s.enemies)s.damage(z,9999);s.step(1/60);}assert(s.result==='win'&&s.time<90);});
 check('소진 레인 위험 예고와 패배 레인 보존',()=>{let s=newSim();s.policeUsed=true;s.police[1].used=true;let z=s.spawn('normal',1,360);assert(s.dangerLanes.includes(1));s.police[1].active=1;assert(!s.dangerLanes.includes(1));s.police[1].active=0;z.x=136;tick(s,.1);assert(s.result==='lose'&&s.breachedLane===1);});
 check('9슬롯 초과 차단',()=>{let s=new Simulation(20,UNITS.map(u=>u.id));assert(s.deck.length===9);});
 check('유발유봉은 같은 레인 고HP 적을 곡사 타격',()=>{let s=newSim(['mortar']);s.money=500;s.place('mortar',1,2);let a=s.spawn('normal',2,600),b=s.spawn('bulky',2,700);tick(s,2.2);assert(a.hp===200&&b.hp===710);});
 check('분무기 부채꼴과 사거리 제한',()=>{let s=newSim(['spray']);s.place('spray',1,2);let a=s.spawn('normal',1,450),b=s.spawn('normal',2,800),c=s.spawn('normal',0,440);tick(s,.8);assert(a.hp===182&&b.hp===200&&c.hp===200);});
 check('냉찜질팩 준비시간·1회 빙결·시간 해제',()=>{let s=newSim(['icepack']);s.place('icepack',2,2);let z=s.spawn('bulky',2,500);tick(s,1.9);assert(z.hp===800&&!z.freeze);tick(s,.5);assert(z.hp===740&&z.freeze>0&&s.units.length===0);let x=z.x;tick(s,1);assert(z.x===x);tick(s,2);assert(z.freeze===0&&z.x<x);});
 check('캡슐연사기 실제 빠른 연사',()=>{let s=newSim(['capsule']);s.place('capsule',1,2);let z=s.spawn('bulky',2,450);tick(s,1.4);assert(s.stats.shots>=4&&z.hp<780);});
 check('약봉투 착탄 범위는 이웃 레인 포함',()=>{let s=newSim(['bag']);s.place('bag',1,2);let a=s.spawn('bulky',2,600),b=s.spawn('bulky',1,610),c=s.spawn('bulky',4,600);tick(s,2.1);assert(a.hp===800-U.bag.damage&&b.hp===800-U.bag.damage&&c.hp===800);});
 return results;
}
export function botAction(sim){for(let z of sim.enemies)if(z.hp>0&&z.x<310&&sim.units.some(u=>u.col===0&&u.lane===z.lane))sim.remove(0,z.lane);const place=(id,c,l)=>id==='counter'&&sim.enemies.some(z=>z.hp>0&&z.lane===l&&z.x<340)?false:sim.place(id,c,l);for(let c of sim.coins)if(!c.collected)sim.collect(c.id);if(sim.tutorial===0)place('counter',0,2);if(sim.tutorial===2)place('rookie',1,2);let lanes=sim.activeLanes.slice().sort((a,b)=>Math.min(1200,...sim.enemies.filter(z=>z.lane===a).map(z=>z.x))-Math.min(1200,...sim.enemies.filter(z=>z.lane===b).map(z=>z.x)));let eco=sim.units.filter(u=>u.type==='counter').length;for(let l of lanes){let threat=sim.enemies.some(z=>z.lane===l&&z.x<720);if(threat&&!sim.units.some(u=>u.lane===l&&u.type==='rookie'))place('rookie',1,l);if(threat&&sim.deck.includes('staff')&&sim.enemies.some(z=>z.lane===l&&z.x<620))place('staff',5,l);}if(eco<5&&(sim.money>=150||eco<2))for(let l of lanes)if(place('counter',0,l))break;for(let l of lanes)if(!sim.units.some(u=>u.lane===l&&u.type==='rookie'))place('rookie',1,l);if(eco<5)for(let l of lanes)if(place('counter',0,l))break;for(let l of lanes){if(sim.deck.includes('veteran'))place('veteran',2,l);else place('rookie',2,l);if(sim.deck.includes('syrup'))place('syrup',3,l);if(sim.deck.includes('roller'))place('roller',4,l);if(sim.deck.includes('dispenser'))place('dispenser',4,l);if(sim.deck.includes('spatula'))place('spatula',6,l);if(sim.deck.includes('staff'))place('staff',5,l);}}
export function qaDeck(stage){let deck=['counter','rookie'];if(stage>=2)deck.push('staff');if(stage===3)deck.push('temp');if(stage>=4)deck.push('syrup');if(stage>=7)deck.push('veteran');if(stage>=9)deck.push(stage===13?'dispenser':stage===17?'spatula':'roller');return deck;}
export function planInput(s){if(s.stopped)return null;let c=s.coins.find(c=>!c.collected);if(c)return {kind:'coin',x:c.x,y:c.y};const able=(id,col,lane)=>s.deck.includes(id)&&s.money>=U[id].cost&&s.cooldowns[id]<.001&&!s.units.some(u=>u.col===col&&u.lane===lane)&&s.activeLanes.includes(lane)&&!(id==='counter'&&s.enemies.some(z=>z.hp>0&&z.lane===lane&&z.x<340));const p=(id,col,lane)=>({kind:'place',id,col,lane});for(let z of s.enemies)if(z.hp>0&&z.x<310){let u=s.units.find(u=>u.lane===z.lane&&u.col===0);if(u)return {kind:'remove',col:0,lane:z.lane};}if(s.tutorial===0)return able('counter',0,2)?p('counter',0,2):null;if(s.tutorial===1)return null;if(s.tutorial===2)return able('rookie',1,2)?p('rookie',1,2):null;let lanes=s.activeLanes.slice().sort((a,b)=>Math.min(1200,...s.enemies.filter(z=>z.lane===a).map(z=>z.x))-Math.min(1200,...s.enemies.filter(z=>z.lane===b).map(z=>z.x))),eco=s.units.filter(u=>u.type==='counter').length;
for(let l of lanes){let threat=s.enemies.some(z=>z.lane===l&&z.x<720);if(threat&&!s.units.some(u=>u.lane===l&&u.type==='rookie')&&able('rookie',1,l))return p('rookie',1,l);if(threat&&s.enemies.some(z=>z.lane===l&&z.x<620)&&able('staff',5,l))return p('staff',5,l);if(s.enemies.some(z=>z.lane===l&&z.x>920&&z.x<1020)&&able('temp',6,l))return p('temp',6,l);}
if(eco<5&&(s.money>=150||eco<2))for(let l of lanes)if(able('counter',0,l))return p('counter',0,l);for(let l of lanes)if(!s.units.some(u=>u.lane===l&&u.type==='rookie')&&able('rookie',1,l))return p('rookie',1,l);if(eco<5)for(let l of lanes)if(able('counter',0,l))return p('counter',0,l);for(let l of lanes){let id=s.deck.includes('veteran')?'veteran':'rookie';if(able(id,2,l))return p(id,2,l);for(let [id,col]of [['syrup',3],['roller',4],['dispenser',4],['spatula',6],['staff',5]])if(able(id,col,l))return p(id,col,l);}return null;}
export function runCampaign(seedOffset=0){let out=[];for(let stage=1;stage<=20;stage++){let s=new Simulation(stage,qaDeck(stage),stage*1979+seedOffset);for(let step=0;step<65000&&!s.result;step++){if(s.awaiting)s.dismiss();botAction(s);s.step(1/60);s.drain();}out.push({stage,seed:s.seed,deck:s.deck,result:s.result,time:s.time,police:s.stats.police,stats:s.stats,bossStage:s.bossStage});}return out;}
