import {U,E,STAGES,BALANCE as B,BOARD as G,TEXT,makeWaves,rng,MAX_DECK,EARLY_PACING,EARLY_CHAT,SKY_MONEY,TUTORIAL_PACING as T} from './data.js';
export class Simulation{
 constructor(stageId,deck,seed=stageId*1979,{tutorial=true}={}){this.stage=STAGES[stageId-1];this.deck=[...new Set(deck)].slice(0,MAX_DECK);this.seed=seed;this.random=rng(seed);this.money=this.stage.initialMoney;this.time=0;this.nextChatter=0;this.chatIndex=0;this.nextSky=SKY_MONEY.first;this.skyRandom=rng(seed^0x51a7);this.units=[];this.enemies=[];this.coins=[];this.shots=[];this.effects=[];this.corpses=[];this.events=[];this.cooldowns=Object.fromEntries(this.deck.map(x=>[x,0]));this.policeUsed=false;this.arrest=null;this.police=Array.from({length:5},()=>({used:false,active:0,x:80}));this.waves=makeWaves(this.stage,seed);this.cursor=0;this.uid=0;this.result=null;this.awaiting=null;this.pauses=new Set();this.eventDone=false;this.boss=null;this.bossStarted=false;this.bossStage=0;this.lastSupport=0;this.group=-1;this.tutorial=stageId===1&&tutorial?0:-1;this.learnClock=0;this.tutorialCleared=false;this.stats={placed:{},killed:{},collected:0,police:0,shots:0,damage:0};this.scheduled=[];if(stageId===1&&!tutorial){this.tutorialCleared=true;for(let i=0;i<EARLY_PACING[1].count;i++)this.waves.push({at:EARLY_PACING[1].first+i*6,lane:i%5,type:'normal',group:0});}}
 emit(type,data={}){this.events.push({type,...data});}
 drain(){return this.events.splice(0);}
 get activeLanes(){return this.tutorial>=0&&this.tutorial<3?[2]:this.tutorial===3?[1,2,3]:[0,1,2,3,4];}
 get dangerLanes(){return this.police.flatMap((p,l)=>p.used&&!p.active&&this.enemies.some(z=>z.hp>0&&z.lane===l&&z.x<370)?[l]:[]);}
 callPolice(){if(this.policeUsed)return false;this.policeUsed=true;this.stats.police=1;this.arrest={elapsed:0,duration:4.8,people:this.enemies.filter(z=>z.hp>0&&z.type!=='boss').map(z=>({...z})),boss:this.enemies.some(z=>z.type==='boss'&&z.hp>0),bossFrom:this.boss?.x};for(let p of this.police){p.used=true;p.active=this.arrest.duration;}for(let z of this.arrest.people)this.stats.killed[z.type]=(this.stats.killed[z.type]||0)+1;this.enemies=this.enemies.filter(z=>z.type==='boss'&&z.hp>0);this.shots=[];this.emit('sound',{name:'police'});this.emit('banner',{text:this.arrest.boss?'112 출동! 일반 좀비 연행 · 왕진상은 뒤로!':TEXT.police});return true;}
 get progress(){return this.stage.id===20&&this.boss?1-this.boss.hp/B.bossHP:Math.min(1,this.time/this.stage.duration);}
 get stopped(){return this.result||this.pauses.size||this.awaiting;}
 point(col,lane){return {x:G.x+col*G.col+G.col/2,y:G.y+lane*G.row+G.row*.84};}
 placementIssue(id,col,lane){if(this.stopped||this.arrest)return 'paused';let d=U[id];if(!d||!this.deck.includes(id))return 'selection';if(col<0||col>=8||!this.activeLanes.includes(lane))return 'closed';if(this.units.some(u=>u.col===col&&u.lane===lane))return 'occupied';if(this.money<d.cost)return 'money';if(this.cooldowns[id]>.001)return 'cooldown';return null;}
 place(id,col,lane){if(this.placementIssue(id,col,lane))return false;let d=U[id];
 let p=this.point(col,lane);let u={id:++this.uid,type:id,col,lane,...p,hp:d.hp,maxHp:d.hp,timer:id==='counter'?3:['temp','icepack'].includes(id)?d.period:d.period*.35,age:0,state:'idle',stateT:0,hurt:0,jam:0,cloud:0,resist:0,windup:null,ready:false,burst:null};this.units.push(u);this.money-=d.cost;this.cooldowns[id]=d.cd;this.stats.placed[id]=(this.stats.placed[id]||0)+1;this.emit('sound',{name:'place'});this.fx('place',p.x,p.y);if(this.tutorial===0&&id==='counter')this.tutorial=1;if(this.tutorial===2&&id==='rookie'){this.tutorial=3;this.learnClock=this.time;this.spawn('normal',2,960);this.scheduled.push({at:this.time+T.sideFirst,type:'normal',lane:1},{at:this.time+T.sideSecond,type:'normal',lane:3});}return true;}
 remove(col,lane){if(this.stopped||this.arrest)return false;let u=this.units.find(u=>u.col===col&&u.lane===lane);if(!u)return false;this.killUnit(u,true);this.emit('sound',{name:'remove'});return true;}
 collect(id){if(this.stopped)return false;let c=this.coins.find(c=>c.id===id&&!c.collected);if(!c)return false;c.collected=true;c.life=.4;this.money+=c.value;this.stats.collected++;this.emit('sound',{name:'coin'});this.fx('money',c.x,c.y,{text:'+'+c.value});if(this.tutorial===1&&!c.sky)this.tutorial=2;return true;}
 spawn(type,lane,x=G.spawn){let d=type==='boss'?{hp:B.bossHP,art:10,speed:.25}:E[type];if(!d||!this.activeLanes.includes(lane))return null;let z={id:++this.uid,type,lane,x,y:this.point(0,lane).y,hp:d.hp,maxHp:d.hp,shield:d.shield||0,age:0,timer:1,ability:5,state:'walk',stateT:0,hurt:0,slow:0,phone:false,windup:null,speech:0,quote:'',shift:null};this.enemies.push(z);if(type==='boss')this.boss=z;return z;}
 fx(kind,x,y,extra={}){if(this.effects.length>=160)this.effects.shift();this.effects.push({kind,x,y,life:kind==='cloud'?3:kind==='blast'?1:.65,max:kind==='cloud'?3:kind==='blast'?1:.65,...extra});}
 damage(z,amount,source='rookie'){if(z.hp<=0)return;if(z.type==='armored'&&z.shield>0&&source!=='roller'){if(!z.speech){z.quote='돌돌이로 포장을 풀어주세요!';z.speech=2;}return;}let n=amount;if(z.shield){let a=Math.min(z.shield,n);z.shield-=a;n-=a;if(!z.shield){if(z.type==='armored'){z.quote='포장 해제!';z.speech=1.5;}this.fx('shield',z.x,z.y);this.emit('sound',{name:'break'});}}z.hp-=n;z.hurt=.17;this.stats.damage+=amount;this.fx('impact',z.x,z.y-35,{source,power:Math.min(2,amount/30)});this.emit('sound',{name:'impact'});if(z.type==='boss'){if(z.hp<=B.bossHP*.65&&this.bossStage<2){this.bossStage=2;this.request('boss2');}else if(z.hp<=B.bossHP*.3&&this.bossStage<3){this.bossStage=3;this.request('boss3');}else if(z.hp<=0)this.win();}else if(z.hp<=0){this.stats.killed[z.type]=(this.stats.killed[z.type]||0)+1;this.fx('defeat',z.x,z.y-35);this.corpses.push({...z,life:.7,total:.7,state:'death'});this.emit('sound',{name:'down'});}}
 killUnit(u,retire=false){u.hp=0;this.units=this.units.filter(a=>a!==u);this.corpses.push({...u,ally:true,retire,life:.6,total:.6,state:'death'});this.fx('puff',u.x,u.y);}
 request(kind){if(!this.awaiting){this.awaiting=kind;this.emit('event',{kind});}}
 dismiss(){let kind=this.awaiting;this.awaiting=null;if(kind==='sales'){for(let id of ['rookie','veteran','temp'])if(this.cooldowns[id]>0)this.cooldowns[id]+=2;this.emit('banner',{text:TEXT.rush});this.rush(6);}
 if(kind==='landlord'){this.emit('banner',{text:TEXT.rush});this.rush(12);}
 if(kind==='bossIntro'){this.bossStarted=true;this.bossStage=1;this.spawn('boss',2,1060);this.lastSupport=this.time;}
 if(kind==='boss2'&&this.boss){let l=Math.max(1,Math.min(3,this.boss.lane));for(let u of this.units)if(Math.abs(u.lane-l)<=1){u.jam=2;u.resist=4;}let to=this.boss.lane===2?1:2;this.boss.shift={from:this.boss.lane,to,t:0};this.boss.lane=to;this.rush(5);}
 if(kind==='boss3'){this.rush(15);this.emit('banner',{text:'마지막 러시 — 다섯 레인을 지켜주세요!'});}
 if(this.boss&&this.boss.hp<=B.bossHP*.3&&this.bossStage===2){this.bossStage=3;this.request('boss3');}else if(this.boss&&this.boss.hp<=0&&this.bossStage===3)this.win();}
 rush(n){for(let i=0;i<n;i++)this.scheduled.push({at:this.time+4+i*1.3,type:this.stage.types[i%this.stage.types.length],lane:i%5});}
 win(){if(this.result)return;this.result='win';this.emit('result',{result:'win'});}
 lose(lane){if(this.result)return;this.result='lose';this.breachedLane=lane;this.emit('result',{result:'lose',lane});}
 hitUnit(u,amount){u.hp-=amount;u.hurt=.2;if(u.hp<=0)this.killUnit(u);}
 fire(u){let d=U[u.type];this.stats.shots++;this.emit('sound',{name:({mortar:'mortar',spray:'spray',icepack:'freeze',capsule:'capsule',bag:'bag',roller:'roll',syrup:'syrup'})[u.type]||'shoot'});if(u.type==='temp'){for(let z of this.enemies)if(z.hp>0&&Math.abs(z.lane-u.lane)<=1&&Math.abs(z.x-u.x)<155)this.damage(z,d.damage,u.type);this.fx('blast',u.x,u.y);this.emit('sound',{name:'blast'});this.killUnit(u,true);return;}
 if(u.type==='spray'){for(let z of this.enemies)if(z.hp>0&&Math.abs(z.lane-u.lane)<=1&&z.x>=u.x-10&&z.x-u.x<200)this.damage(z,d.damage,u.type);this.fx('spray',u.x,u.y-30);return;}
 if(u.type==='icepack'){for(let z of this.enemies)if(z.hp>0&&Math.abs(z.lane-u.lane)<=1&&Math.abs(z.x-u.x)<145){this.damage(z,d.damage,u.type);z.freeze=2.5;}this.fx('freeze',u.x,u.y-30);this.killUnit(u,true);return;}
 if(u.type==='mortar'||u.type==='bag'){let targets=this.enemies.filter(z=>z.hp>0&&z.lane===u.lane&&z.x>=u.x-15);targets.sort((a,b)=>u.type==='mortar'?b.hp-a.hp:a.x-b.x);let z=targets[0];if(z)this.shots.push({id:++this.uid,type:u.type,arc:true,age:0,duration:.75,x:u.x,y:u.y-35,fromX:u.x,fromY:u.y-35,toX:z.x,toY:z.y-35,target:z.id,lane:u.lane,damage:d.damage,life:1});return;}
 if(u.type==='spatula'){let z=this.enemies.filter(z=>z.hp>0&&z.lane===u.lane&&z.x>=u.x-15&&z.x-u.x<105).sort((a,b)=>a.x-b.x)[0];if(z)this.damage(z,d.damage,u.type);this.fx('slash',u.x+45,u.y-32);return;}
 this.fx('muzzle',u.x+30,u.y-35,{source:u.type});let lanes=u.type==='dispenser'?[u.lane-1,u.lane,u.lane+1].filter(l=>l>=0&&l<5):[u.lane];for(let lane of lanes)this.shots.push({id:++this.uid,x:u.x+23,y:this.point(0,lane).y-35,lane,type:u.type,damage:d.damage,hits:new Set(),life:4});if(u.type==='veteran'&&!u.burst)u.burst={left:.16};}
 step(dt){if(this.stopped)return;dt=Math.min(dt,.05);if(this.arrest){this.arrest.elapsed+=dt;if(this.arrest.boss&&this.boss){let p=Math.max(0,Math.min(1,(this.arrest.elapsed/this.arrest.duration-.25)/.75));this.boss.x=this.arrest.bossFrom+(1060-this.arrest.bossFrom)*(p*p*(3-2*p));this.boss.state='hurt';}if(this.arrest.elapsed>=this.arrest.duration){let boss=this.arrest.boss;this.arrest=null;for(let p of this.police)p.active=0;if(boss){this.boss.state='walk';this.boss.stateT=0;this.emit('banner',{text:'왕진상이 다시 다가옵니다! 직접 막아주세요.'});}}return;}this.time+=dt;
 for(let id in this.cooldowns)this.cooldowns[id]=Math.max(0,this.cooldowns[id]-dt);
 if(this.time>=this.nextSky){let r=this.skyRandom;this.coins.push({id:++this.uid,x:G.x+35+r()*(G.cols*G.col-70),y:195,targetY:260+r()*300,sky:true,value:SKY_MONEY.value,life:B.coinLife+5,collected:false});this.nextSky=this.time+(this.time<SKY_MONEY.openingUntil?SKY_MONEY.openingGap:SKY_MONEY.minGap+r()*(SKY_MONEY.maxGap-SKY_MONEY.minGap));}for(let c of this.coins){c.life-=dt;if(c.sky&&!c.collected)c.y=Math.min(c.targetY,c.y+SKY_MONEY.fallSpeed*dt);}this.coins=this.coins.filter(c=>c.life>0);for(let f of this.effects)f.life-=dt;this.effects=this.effects.filter(f=>f.life>0);for(let c of this.corpses)c.life-=dt;this.corpses=this.corpses.filter(c=>c.life>0);
 if(this.tutorial===3&&this.time-this.learnClock>T.openFive){this.tutorial=4;this.tutorialCleared=true;for(let i=0;i<T.finalCount;i++)this.scheduled.push({at:this.time+T.finalDelay+i*T.finalGap,lane:i%5,type:'normal'});}
 if(this.stage.event&&!this.eventDone&&this.time>=this.stage.duration*.48){this.eventDone=true;this.request(this.stage.event);return;}
 if(this.stage.id===20&&!this.bossStarted&&this.time>=70){this.request('bossIntro');return;}
 while(this.cursor<this.waves.length&&this.waves[this.cursor].at<=this.time){let w=this.waves[this.cursor++];this.spawn(w.type,w.lane);if(w.group!==this.group){this.group=w.group;this.emit('wave',{group:w.group});if(w.group>0)this.emit('banner',{text:this.stage.id===5?TEXT.lunch:this.stage.id===12?TEXT.children:'좀비들이 몰려옵니다!'});}}
 for(let s of this.scheduled.filter(s=>s.at<=this.time))this.spawn(s.type,s.lane);this.scheduled=this.scheduled.filter(s=>s.at>this.time);
 if(this.bossStarted&&this.boss?.hp>0&&this.time-this.lastSupport>(this.bossStage===3?13:24)){this.lastSupport=this.time;this.spawn(this.stage.types[Math.floor(this.random()*this.stage.types.length)],Math.floor(this.random()*5));}
 for(let u of [...this.units]){if(u.hp<=0)continue;u.age+=dt;u.stateT+=dt;u.hurt=Math.max(0,u.hurt-dt);u.jam=Math.max(0,u.jam-dt);u.cloud=Math.max(0,u.cloud-dt);u.resist=Math.max(0,u.resist-dt);if(u.jam>0)continue;let udt=dt*(u.cloud>0?.7:1);let d=U[u.type];
 if(u.type==='counter'){u.timer-=dt;if(u.timer<=0){u.timer=d.period;this.coins.push({id:++this.uid,x:u.x,y:u.y-45,value:25,life:B.coinLife,collected:false});u.state='attack';u.stateT=0;}else if(u.stateT>.4)u.state='idle';continue;}
 if(u.type==='staff'){u.state=this.enemies.some(z=>z.hp>0&&z.lane===u.lane&&Math.abs(z.x-u.x)<65)?'attack':'idle';continue;}
 if(['temp','icepack'].includes(u.type)&&!u.ready){u.timer-=dt;if(u.timer<=0){u.ready=true;u.state='idle';}continue;}
 if(u.burst){u.burst.left-=udt;if(u.burst.left<=0){let old=u.burst;this.fire(u);u.burst=null;}}
 if(u.windup){u.windup.left-=udt;if(u.windup.left<=0){this.fire(u);u.windup=null;u.timer=d.period;u.stateT=0;}continue;}
 u.timer-=udt;if(u.state==='attack'&&u.stateT>.3)u.state='idle';let target=this.enemies.some(z=>z.hp>0&&(['dispenser','spray','icepack'].includes(u.type)?Math.abs(z.lane-u.lane)<=1:z.lane===u.lane)&&z.x>=u.x-15&&z.x<1160&&(u.type==='spray'?z.x-u.x<200:['temp','icepack'].includes(u.type)?z.x-u.x<120:u.type==='spatula'?z.x-u.x<105:true));if(target&&u.timer<=0){u.state='attack';u.stateT=0;u.windup={left:u.type==='temp'?.3:u.type==='capsule'?.04:.15};}}
 if(this.stage.id<=7&&this.time>=this.nextChatter&&!this.enemies.some(z=>z.hp>0&&z.speech>0)){let speaker=this.enemies.find(z=>z.hp>0&&!z.chatted&&z.x<1100);if(speaker){speaker.chatted=true;speaker.quote=EARLY_CHAT.lines[this.chatIndex++%EARLY_CHAT.lines.length];speaker.speech=EARLY_CHAT.duration;this.nextChatter=this.time+EARLY_CHAT.gap;}}
 for(let z of this.enemies){if(z.hp<=0)continue;z.age+=dt;z.stateT+=dt;z.hurt=Math.max(0,z.hurt-dt);z.slow=Math.max(0,z.slow-dt);z.speech=Math.max(0,z.speech-dt);if(z.freeze>0){z.freeze=Math.max(0,z.freeze-dt);z.state='hurt';continue;}if(z.shift){z.shift.t+=dt;let p=Math.min(1,z.shift.t/1.2);z.y=this.point(0,z.shift.from).y+(this.point(0,z.shift.to).y-this.point(0,z.shift.from).y)*p;if(p===1)z.shift=null;continue;}
 let blocked=this.units.filter(u=>u.lane===z.lane&&u.x<=z.x+12&&z.x-u.x<58).sort((a,b)=>b.x-a.x)[0];if(blocked){z.state='attack';z.timer-=dt;if(z.timer<=0){this.hitUnit(blocked,z.type==='bulky'?B.bulkyDamage:z.type==='boss'?B.bossDamage:B.enemyDamage);z.timer=z.type==='bulky'?B.bulkyAttack:z.type==='boss'?B.bossAttack:B.enemyAttack;z.stateT=0;this.emit('sound',{name:'hurt'});}}else{z.state='walk';let speed=z.type==='boss'?.25:E[z.type].speed;if(z.type==='drunk')speed=.6+(Math.sin(z.age*1.4+z.id)*.5+.5)*.9;if(z.type==='phone'){if(!z.phone&&z.x<800){z.phone=true;z.speech=1;z.quote='…앗!';}if(z.phone)speed=1.9;}z.x-=B.move*speed*(z.slow>0?B.slowFactor:1)*dt;}
 if(['cold','complaint'].includes(z.type)){z.ability-=dt;if(z.ability<=0){z.ability=z.type==='cold'?6:7;let victims=this.units.filter(u=>Math.abs(u.lane-z.lane)<=1&&z.x-u.x>0&&z.x-u.x<200);if(z.type==='cold'){this.fx('cloud',z.x-90,z.y-30);for(let u of victims)u.cloud=3;}else{z.quote=TEXT.complaints[Math.floor(this.random()*TEXT.complaints.length)];z.speech=2.4;for(let u of victims)if(!u.resist){u.jam=1;u.resist=4;}}}}
 if(z.x<G.end){if(!this.policeUsed){this.callPolice();return;}this.lose(z.lane);return;}
 }
 for(let s of this.shots){if(s.arc){s.age+=dt;let p=Math.min(1,s.age/s.duration);s.x=s.fromX+(s.toX-s.fromX)*p;s.y=s.fromY+(s.toY-s.fromY)*p-Math.sin(Math.PI*p)*85;if(p===1){if(s.type==='bag'){for(let z of this.enemies)if(z.hp>0&&Math.abs(z.lane-s.lane)<=1&&Math.abs(z.x-s.toX)<110)this.damage(z,s.damage,s.type);this.fx('blast',s.toX,s.toY);}else{let z=this.enemies.find(z=>z.id===s.target);if(z)this.damage(z,s.damage,s.type);this.fx('hit',s.toX,s.toY);}s.life=0;}continue;}let old=s.x;s.x+=B.projectileSpeed*dt;s.life-=dt;let targets=this.enemies.filter(z=>z.hp>0&&z.lane===s.lane&&!s.hits.has(z.id)&&z.x+22>=old&&z.x-22<=s.x).sort((a,b)=>a.x-b.x);for(let z of targets){s.hits.add(z.id);this.damage(z,s.damage,s.type);if(s.type==='syrup')z.slow=B.slowDuration;if(s.type!=='roller'){s.life=0;break;}}}
 this.shots=this.shots.filter(s=>s.life>0&&s.x<1180);this.enemies=this.enemies.filter(z=>z.hp>0||z.type==='boss');
 if(this.awaiting||this.result)return;if(this.stage.id!==20&&this.cursor===this.waves.length&&!this.scheduled.length&&!this.enemies.length&&(this.stage.id!==1||this.tutorialCleared)){this.win();}
 }
 snapshot(){return {stage:this.stage.id,time:this.time,money:this.money,result:this.result,tutorial:this.tutorial,cursor:this.cursor,waves:this.waves.length,units:this.units.map(u=>({type:u.type,col:u.col,lane:u.lane,hp:u.hp,jam:u.jam,timer:u.timer})),enemies:this.enemies.map(z=>({type:z.type,x:z.x,lane:z.lane,hp:z.hp,shield:z.shield})),coins:this.coins.map(c=>({id:c.id,x:c.x,y:c.y,life:c.life,collected:c.collected})),cooldowns:{...this.cooldowns},policeUsed:this.policeUsed,arrest:this.arrest,police:this.police.map(p=>({...p})),awaiting:this.awaiting,bossStage:this.bossStage,stats:this.stats};}
}
